const courses = [
  {
    id: "1",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HKnp.png",
  },
  {
    id: "2",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HCFt.png",
  },
  {
    id: "3",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HfMN.png",
  },
  {
    id: "4",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HKnp.png",
  },
  {
    id: "5",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HCFt.png",
  },
  {
    id: "6",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HKnp.png",
  },
  {
    id: "7",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HqPI.png",
  },
  {
    id: "8",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HCFt.png",
  },
  {
    id: "9",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HKnp.png",
  },
  {
    id: "10",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HfMN.png",
  },
  {
    id: "11",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HqPI.png",
  },
  {
    id: "12",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HKnp.png",
  },
  {
    id: "13",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HCFt.png",
  },
  {
    id: "14",
    name: "Java",
    price: 100000,
    author: "Mosh Hamidani",
    img: "https://iili.io/d6HKnp.png",
  },
];

export default courses;
